---

- block:
  - name: check if tidalcycles atom plugin is installed
    shell: apm list -i
    register: tidatin
    changed_when: "not tidatin.stdout is search('tidalcycles')"
  
  - name: install tidalcycles atom plugin
    shell: apm install tidalcycles
    when: "not tidatin.stdout is search('tidalcycles')"

  - name: create/replace atom config ~/.atom/config.cson (taking a backup)
    template:
      src: templates/config.cson.template
      dest: "/home/{{ansible_env.SUDO_USER}}/.atom/config.cson"
      mode: 0640
      backup: yes
    tags:
    - config

  become: yes
  become_method: su
  become_user: "{{ansible_env.SUDO_USER}}"
  become_flags: '-s /bin/bash'

- block:
  - name: get default BootTidal.hs locations
    shell: ghc-pkg field tidal data-dir | head -n 1 | awk '{print $2}'
    register: tidloc
    changed_when: False

  - name: "set default BootTidal.hs location ({{ tidloc.stdout }})"
    set_fact:
      boottidal_hs: "{{ tidloc.stdout }}/BootTidal.hs"

  - name: create required config scripts directory
    file:
      path: "/home/{{ansible_env.SUDO_USER}}/.local/share/ansible-tidalcycles/scripts/"
      state: directory
      recurse: yes

  - name: copy mutable-instruments params file to scripts dir
    get_url:
      url: https://raw.githubusercontent.com/cleary/ansible-tidalcycles/master/files/mutable-instruments-ugens_parameters.hs
      dest: "/home/{{ansible_env.SUDO_USER}}/.local/share/ansible-tidalcycles/scripts/mutable-instruments-ugens_parameters.hs"

  - name: load mutable-instruments parameter file in BootTidal.hs
    lineinfile:
        path: "{{ boottidal_hs }}"
        insertbefore: '^:set prompt (.*$)'
        line: ":script /home/{{ansible_env.SUDO_USER}}/.local/share/ansible-tidalcycles/scripts/mutable-instruments-ugens_parameters.hs"

  become: yes
  become_method: su
  become_user: "{{ansible_env.SUDO_USER}}"
  become_flags: '-s /bin/bash'
  when: sc_ugens is defined and "mutable-instruments" in sc_ugens
