---

- block:
  - name: check if tidalcycles atom plugin is installed
    shell: apm list -i
    register: tidatin
    changed_when: "not tidatin.stdout is search('tidalcycles')"
  
  - name: install tidalcycles atom plugin
    shell: apm install tidalcycles
    when: "not tidatin.stdout is search('tidalcycles')"
  become: yes
  become_method: su
  become_user: "{{ansible_env.SUDO_USER}}"
  become_flags: '-s /bin/bash'
