---

- name: install dependencies
  apt:
    state: latest
    update_cache: yes
    install_recommends: no
    name: 
      - apt-transport-https
      - dirmngr
      - gpg
      - gpg-agent

- name: add apt_keys for atom/packagecloud.io repository
  apt_key:
    id: DE9E3B09
    state: present
    keyserver: "keyserver.ubuntu.com"

- name: add atom/packagecloud.io repository
  apt_repository:
    repo: deb https://packagecloud.io/AtomEditor/atom/any/ any main
    filename: atom.list
    state: present
    validate_certs: yes
    update_cache: yes
